Update README with instructions for installing requirements and indexing to the staging server
vectara/web-crawler pull request #1
Opened 2023-02-02 22:11 UTC by cjcenizal

Per https://vectara.slack.com/archives/C037Z2Z7QHZ/p1675365874084489

2023-02-13 16:53 UTC, eskibars requested changes
Thanks @cjcenizal !  Left some comments

2023-02-13 16:53 UTC, eskibars commented on README.md
> +```
The more elegant way of doing this in python is `pip3 install -r requirements.txt` which installs specific versions as needed as described in requirements.txt (as well as dependencies).  The rest of these are transitive dependencies.  All of the required dependencies are in there.  It also applies across any OS as well.

2023-02-13 16:53 UTC, eskibars commented on README.md
> +--auth-url https://vectara-prod-{CUSTOMER_ID}.auth.us-west-2.amazoncognito.com --indexing-endpoint h.indexing.vectara.dev
Customers don't need this.  It will auto-determine the correct auth URL and has indexing endpoints baked in for prod.  We probably shouldn't document how to use our staging on a public repo.  Can you remove?

2023-02-13 17:52 UTC, cjcenizal commented
Thanks @eskibars, updated with your feedback. Could you please take another look?

2023-02-14 00:19 UTC, eskibars requested changes
Sorry, another I didn't see before: it looks like you've included the contents of 3 pdfs from a crawl you did in the PR.  Can you please remove these?
- https://github.com/vectara/web-crawler/blob/7535b311b8c2ac53c28f39687fe485c58cb40ffe/1675371437.565749.pdf
- https://github.com/vectara/web-crawler/blob/7535b311b8c2ac53c28f39687fe485c58cb40ffe/1675371546.033996.pdf
- https://github.com/vectara/web-crawler/blob/7535b311b8c2ac53c28f39687fe485c58cb40ffe/1675371766.01194.pdf

2023-02-14 00:35 UTC, cjcenizal commented
Ugh, great catch. Fixed.

2023-02-14 00:39 UTC, eskibars commented
Thanks.  This LGTM!

2023-02-14 00:39 UTC, eskibars approved these changes

2023-02-14 00:58 UTC, merged